script:
  path: ./static/scripts
settings:
  application:
    domain: localhost:8002
    host: 0.0.0.0
    ishttps: false
    mode: dev
    name: ferry-test
    port: "8002"
    readtimeout: 1
    writertimeout: 2
  database:
    dbtype: mysql
    host: 127.0.0.1
    name: ferry
    password: ferry@2020
    port: 3306
    username: ferry
  email:
    alias: ferry
    host: smtp.163.com
    pass: REYVECRYOZEZIFKL
    port: 465
    user: fdevops@163.com
  gorm:
    logmode: 0
    maxidleconn: 0
    maxopenconn: 20000
  jwt:
    secret: ferry
    timeout: 3600
  log:
    dir: logs
    operdb: false
  ssl:
    key: keystring
    pem: temp/pem.pem
